/**
 * GitHub API client for creating PRs with improved documentation.
 *
 * Uses Octokit to: create branch → commit file → open PR.
 * The developer reviews the diff in their IDE.
 */

import { Octokit } from '@octokit/rest';

export interface CreatePrInput {
    repoOwner: string;
    repoName: string;
    filePath: string;
    newContent: string;
    title: string;
    body: string;
    baseBranch: string;
}

export interface CreatePrResult {
    prUrl: string;
    prNumber: number;
    branchName: string;
}

export async function createPr(input: CreatePrInput): Promise<CreatePrResult> {
    const { repoOwner, repoName, filePath, newContent, title, body, baseBranch } = input;

    const token = process.env.GITHUB_TOKEN;
    if (!token) {
        throw new Error('GITHUB_TOKEN environment variable is not set');
    }

    const octokit = new Octokit({ auth: token });

    // Step 1: Get the base branch SHA
    const { data: refData } = await octokit.git.getRef({
        owner: repoOwner,
        repo: repoName,
        ref: `heads/${baseBranch}`,
    });
    const baseSha = refData.object.sha;
    console.error(`[github] Base branch '${baseBranch}' at SHA: ${baseSha.substring(0, 7)}`);

    // Step 2: Create a new branch
    const timestamp = Date.now();
    const slug = filePath.split('/').pop()?.replace(/\.\w+$/, '') || 'doc';
    const branchName = `perseverance/ai-readiness-${slug}-${timestamp}`;

    await octokit.git.createRef({
        owner: repoOwner,
        repo: repoName,
        ref: `refs/heads/${branchName}`,
        sha: baseSha,
    });
    console.error(`[github] Created branch: ${branchName}`);

    // Step 3: Get current file SHA (needed for update)
    let fileSha: string | undefined;
    try {
        const { data: fileData } = await octokit.repos.getContent({
            owner: repoOwner,
            repo: repoName,
            path: filePath,
            ref: branchName,
        });
        if (!Array.isArray(fileData) && 'sha' in fileData) {
            fileSha = fileData.sha;
        }
    } catch {
        console.error(`[github] File '${filePath}' not found on base — will create new`);
    }

    // Step 4: Commit the improved file
    await octokit.repos.createOrUpdateFileContents({
        owner: repoOwner,
        repo: repoName,
        path: filePath,
        message: `docs: improve AI-readiness for ${filePath.split('/').pop()}\n\nImprovements generated by Perseverance Writer Agent based on Lensy scan.`,
        content: Buffer.from(newContent).toString('base64'),
        sha: fileSha,
        branch: branchName,
    });
    console.error(`[github] Committed improved file to ${branchName}`);

    // Step 5: Create the PR
    const { data: pr } = await octokit.pulls.create({
        owner: repoOwner,
        repo: repoName,
        title,
        body,
        head: branchName,
        base: baseBranch,
    });
    console.error(`[github] PR created: ${pr.html_url}`);

    return {
        prUrl: pr.html_url,
        prNumber: pr.number,
        branchName,
    };
}
